// "use client";
import Link from 'next/link'
import './globals.css'
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import InputBase from '@mui/material/InputBase';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import SearchIcon from '@mui/icons-material/Search';

export const metadata = {
  title: '모든 예약을 도와줄게',
  description: 'Generated by jh&hs',
}

export default async function RootLayout({ children }) {
  // const resp = await fetch('http://localhost:9999/topics');
  // const topics = await resp.json();
  return (
    // 헤드태그,상단메뉴 넣음
    <html>
      <body>
        <AppBar position="static" className='header'>
          <Toolbar>
            <IconButton
              edge="start"
              color='white'
              aria-label="menu"
              sx={{ mr: 1 }}
            >
              <MenuIcon />
            </IconButton>
            <Typography variant="h5" component="div" sx={{ flexGrow: 1 }}>
              <Link href="/">지금갑니다</Link>
            </Typography>
            <Typography variant="h5" component="div" sx={{ flexGrow: 1 }}>
              <Link href="/list">db테스트</Link>
            </Typography>
            <div>
              <InputBase
                placeholder="검색어를 입력해주세요"
                inputProps={{ 'aria-label': 'search' }}
              />
              <IconButton type="submit" aria-label="search">
                <SearchIcon />
              </IconButton>
            </div>
            <Button color="inherit">
              <Link href="/login">로그인</Link>
            </Button>
          </Toolbar>
        </AppBar>
        <Box>
          {children}
        </Box>
        {/* <ul className='title'>
          {topics.map((topic) => {
            return <li key={topic.id}>
              {topic.title}
            </li>
          })}
        </ul> */}
      </body>
    </html>
  )
}
