"use client";
import React from "react";
import AdCarousel from "./_components/slide";
import List from "./_components/list";

export const metadata = {
  title: "포장의, 포장에 의한, 포장을 위한",
  description: "Generated by jh&hs",
};

export default function Home() {
  return (
    <>
      <AdCarousel />
      <List />
    </>
  );
}
